# Use a slim version of the Python base image
FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Install dependencies
COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the application code
COPY app.py app.py

# Expose the port the app runs on
EXPOSE 8080

# Run the application
CMD ["python", "app.py"]
