# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: contact_grpc.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'contact_grpc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x63ontact_grpc.proto\x12\nhelloworld\"v\n\x0e\x43ontactRequest\x12\n\n\x02um\x18\x01 \x01(\t\x12\n\n\x02\x64m\x18\x02 \x01(\t\x12\x16\n\x0etimestamp_sent\x18\x03 \x01(\t\x12\x18\n\x10timestamp_actual\x18\x04 \x01(\t\x12\x1a\n\x12\x63ommunication_type\x18\x05 \x01(\t\"!\n\x0f\x43ontactResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2[\n\rLoggerService\x12J\n\rContactServer\x12\x1a.helloworld.ContactRequest\x1a\x1b.helloworld.ContactResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'contact_grpc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONTACTREQUEST']._serialized_start=34
  _globals['_CONTACTREQUEST']._serialized_end=152
  _globals['_CONTACTRESPONSE']._serialized_start=154
  _globals['_CONTACTRESPONSE']._serialized_end=187
  _globals['_LOGGERSERVICE']._serialized_start=189
  _globals['_LOGGERSERVICE']._serialized_end=280
# @@protoc_insertion_point(module_scope)
